server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      #habilitar como gateway
      enabled: true
      discovery:
        locator:
          #usar servidor de descubrimiento para encontrar direcciones
          enabled: true

eureka:
  client:
    serviceURL:
      #url de eureka
      defaultZone: http://eureka:8761/eureka/
    #indica que debe registrarse en eureka
    register-with-eureka: true
    #indica que puede obtener una lista de servicios registrados en eureka
    fetch-registry: true
    healthcheck:
      #habilitar comprobacion de salud (heart beats)
      enabled: true
  instance:
    #ID de instancia, con este id se registran en eureka
    instance-id: ${spring.application.name}:${random.uuid}
    #frecuencia de heartbreats
    lease-renewal-interval-in-seconds: 30
    #tiempo limite para que se considere fallido
    lease-expiration-duration-in-seconds: 65